# Generated by Django 6.1 on 2026-09-01 16:55

import colony.models
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colony', '0001_enable_btree_gist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('species', models.CharField(default='Mus musculus', max_length=100)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('retired_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'animal',
            },
        ),
        migrations.CreateModel(
            name='Cage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cage_code', models.CharField(max_length=50)),
                ('cage_type', models.CharField(choices=[('standard', 'Standard'), ('breeding', 'Breeding'), ('isolation', 'Isolation')], default='standard', max_length=20)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('retired_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cage',
            },
        ),
        migrations.CreateModel(
            name='AnimalCageAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('system_from', models.DateTimeField(auto_now_add=True)),
                ('system_to', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'animal_cage_assignment',
            },
        ),
        migrations.CreateModel(
            name='AnimalLocalIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier_type', models.CharField(choices=[('ear_tag', 'Ear tag'), ('ear_punch', 'Ear punch'), ('toe_number', 'Toe number'), ('other', 'Other')], max_length=20)),
                ('value', models.CharField(max_length=50)),
                ('assigned_date', models.DateField()),
                ('retired_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'animal_local_identifier',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=100)),
                ('row_id', models.CharField(max_length=64)),
                ('action', models.CharField(choices=[('insert', 'Insert'), ('update', 'Update'), ('delete', 'Delete')], max_length=10)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_log',
            },
        ),
        migrations.CreateModel(
            name='AuditOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(max_length=50)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'audit_operation',
            },
        ),
        migrations.CreateModel(
            name='BreedingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formed_date', models.DateField()),
                ('dissolved_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'breeding_unit',
            },
        ),
        migrations.CreateModel(
            name='BreedingUnitAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('sire', 'Sire'), ('dam', 'Dam')], max_length=10)),
                ('joined_date', models.DateField()),
                ('removed_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'breeding_unit_animal',
            },
        ),
        migrations.CreateModel(
            name='CageRackPositionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('system_from', models.DateTimeField(auto_now_add=True)),
                ('system_to', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'cage_rack_position_assignment',
            },
        ),
        migrations.CreateModel(
            name='HusbandryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('intake', 'Intake'), ('cage_change', 'Cage change'), ('health_check', 'Health check'), ('weight', 'Weight'), ('treatment', 'Treatment'), ('death', 'Death'), ('transfer', 'Transfer'), ('weaning', 'Weaning'), ('tail_snip', 'Tail snip')], max_length=20)),
                ('event_datetime', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'husbandry_event',
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255)),
                ('file_hash', models.CharField(help_text='SHA-256 hex digest of the raw file bytes.', max_length=64)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('validated', 'Validated'), ('validation_failed', 'Validation failed'), ('committed', 'Committed'), ('committed_with_errors', 'Committed with errors'), ('undone', 'Undone')], default='uploaded', max_length=30)),
            ],
            options={
                'db_table': 'import_batch',
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('raw_data', models.JSONField()),
                ('parse_status', models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('invalid', 'Invalid'), ('skipped', 'Skipped'), ('committed', 'Committed')], default='pending', max_length=20)),
                ('validation_errors', models.JSONField(blank=True, null=True)),
                ('created_record_type', models.CharField(blank=True, max_length=50)),
                ('created_record_id', models.CharField(blank=True, help_text="Traceability only — NOT the undo mechanism. Undo replays audit_log rows under the batch's audit_operation instead.", max_length=64)),
            ],
            options={
                'db_table': 'import_row',
            },
        ),
        migrations.CreateModel(
            name='Litter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('birth_date', models.DateField()),
                ('weaning_date', models.DateField(blank=True, null=True)),
                ('number_born', models.PositiveIntegerField(blank=True, null=True)),
                ('number_weaned', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'litter',
            },
        ),
        migrations.CreateModel(
            name='LitterParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('dam', 'Dam'), ('sire', 'Sire')], max_length=10)),
                ('confidence', models.CharField(choices=[('confirmed', 'Confirmed'), ('presumed', 'Presumed'), ('possible', 'Possible')], default='presumed', max_length=10)),
            ],
            options={
                'db_table': 'litter_parent',
            },
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack_code', models.CharField(max_length=50)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rack',
            },
        ),
        migrations.CreateModel(
            name='RackPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_label', models.CharField(max_length=50)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rack_position',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('building', models.CharField(blank=True, max_length=100)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'strain',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('pi', 'Principal Investigator'), ('lab_manager', 'Lab Manager'), ('researcher', 'Researcher'), ('student', 'Student'), ('veterinarian', 'Facility Veterinarian')], max_length=20)),
            ],
            options={
                'db_table': 'user_role',
            },
        ),
        migrations.CreateModel(
            name='AnimalCurrentLocation',
            fields=[
                ('animal', models.OneToOneField(db_column='animal_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='current_location', serialize=False, to='colony.animal')),
                ('valid_from', models.DateTimeField()),
            ],
            options={
                'db_table': 'animal_current_location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CageCurrentLocation',
            fields=[
                ('cage', models.OneToOneField(db_column='cage_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='current_location', serialize=False, to='colony.cage')),
                ('valid_from', models.DateTimeField()),
            ],
            options={
                'db_table': 'cage_current_location',
                'managed': False,
            },
        ),
        migrations.AddConstraint(
            model_name='cage',
            constraint=models.UniqueConstraint(condition=models.Q(('retired_at__isnull', True)), fields=('cage_code',), name='cage_code_active_unique'),
        ),
        migrations.AddField(
            model_name='animalcageassignment',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cage_assignments', to='colony.animal'),
        ),
        migrations.AddField(
            model_name='animalcageassignment',
            name='cage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='animal_assignments', to='colony.cage'),
        ),
        migrations.AddField(
            model_name='animalcageassignment',
            name='correction_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='corrections', to='colony.animalcageassignment'),
        ),
        migrations.AddField(
            model_name='animalcageassignment',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='animallocalidentifier',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='local_identifiers', to='colony.animal'),
        ),
        migrations.AddField(
            model_name='auditoperation',
            name='performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditoperation',
            name='reverses_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='reversed_by_operations', to='colony.auditoperation'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='log_entries', to='colony.auditoperation'),
        ),
        migrations.AddField(
            model_name='breedingunit',
            name='cage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='breeding_units', to='colony.cage'),
        ),
        migrations.AddField(
            model_name='breedingunitanimal',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='breeding_memberships', to='colony.animal'),
        ),
        migrations.AddField(
            model_name='breedingunitanimal',
            name='breeding_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='members', to='colony.breedingunit'),
        ),
        migrations.AddField(
            model_name='cagerackpositionassignment',
            name='cage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='position_assignments', to='colony.cage'),
        ),
        migrations.AddField(
            model_name='cagerackpositionassignment',
            name='correction_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='corrections', to='colony.cagerackpositionassignment'),
        ),
        migrations.AddField(
            model_name='cagerackpositionassignment',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HusbandryEventDeath',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='death_detail', serialize=False, to='colony.husbandryevent')),
                ('cause', models.TextField(blank=True)),
                ('method', models.CharField(choices=[('found_dead', 'Found dead'), ('euthanasia_scheduled', 'Euthanasia (scheduled)'), ('euthanasia_clinical', 'Euthanasia (clinical)')], max_length=30)),
            ],
            options={
                'db_table': 'husbandry_event_death',
            },
        ),
        migrations.CreateModel(
            name='HusbandryEventHealthCheck',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='health_check_detail', serialize=False, to='colony.husbandryevent')),
                ('body_condition_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('findings', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'husbandry_event_health_check',
            },
        ),
        migrations.CreateModel(
            name='HusbandryEventTailSnip',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tail_snip_detail', serialize=False, to='colony.husbandryevent')),
                ('sent_to_lab', models.CharField(blank=True, max_length=200)),
                ('result_status', models.CharField(blank=True, max_length=30)),
                ('result', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'husbandry_event_tail_snip',
            },
        ),
        migrations.CreateModel(
            name='HusbandryEventTreatment',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='treatment_detail', serialize=False, to='colony.husbandryevent')),
                ('drug_name', models.CharField(max_length=200)),
                ('dose', models.CharField(blank=True, max_length=100)),
                ('route', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'husbandry_event_treatment',
            },
        ),
        migrations.CreateModel(
            name='HusbandryEventWeight',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='weight_detail', serialize=False, to='colony.husbandryevent')),
                ('weight_grams', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'husbandry_event_weight',
            },
        ),
        migrations.AddField(
            model_name='husbandryevent',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='husbandry_events', to='colony.animal'),
        ),
        migrations.AddField(
            model_name='husbandryevent',
            name='cage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='husbandry_events', to='colony.cage'),
        ),
        migrations.AddField(
            model_name='husbandryevent',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='animalcageassignment',
            name='husbandry_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cage_assignments', to='colony.husbandryevent'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='audit_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='colony.auditoperation'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importrow',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='colony.importbatch'),
        ),
        migrations.AddField(
            model_name='importrow',
            name='matched_animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='colony.animal'),
        ),
        migrations.AddField(
            model_name='litter',
            name='breeding_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='litters', to='colony.breedingunit'),
        ),
        migrations.AddField(
            model_name='husbandryevent',
            name='litter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='husbandry_events', to='colony.litter'),
        ),
        migrations.AddField(
            model_name='animal',
            name='origin_litter',
            field=models.ForeignKey(blank=True, help_text='Null if not born in-colony (e.g. purchased animal).', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pups', to='colony.litter'),
        ),
        migrations.AddField(
            model_name='litterparent',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='litters_parented', to='colony.animal'),
        ),
        migrations.AddField(
            model_name='litterparent',
            name='litter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='parents', to='colony.litter'),
        ),
        migrations.AddField(
            model_name='rackposition',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='positions', to='colony.rack'),
        ),
        migrations.AddField(
            model_name='cagerackpositionassignment',
            name='rack_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cage_assignments', to='colony.rackposition'),
        ),
        migrations.AddField(
            model_name='rack',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='racks', to='colony.room'),
        ),
        migrations.AddField(
            model_name='animallocalidentifier',
            name='room',
            field=models.ForeignKey(help_text="Denormalized scope for the uniqueness constraint below. Must be kept in sync with the animal's current room (service-layer responsibility, not enforced by the schema).", on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='colony.room'),
        ),
        migrations.AddField(
            model_name='animal',
            name='strain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='colony.strain'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='scope_room',
            field=models.ForeignKey(blank=True, help_text='Optional: restrict this role to a specific room.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='colony.room'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colony_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditoperation',
            index=models.Index(fields=['reverses_operation'], name='audit_opera_reverse_edb923_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['operation'], name='audit_log_operati_035321_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['table_name', 'row_id', 'created_at'], name='audit_log_table_n_c821e7_idx'),
        ),
        migrations.AddConstraint(
            model_name='breedingunitanimal',
            constraint=models.UniqueConstraint(fields=('breeding_unit', 'animal', 'joined_date'), name='breeding_unit_animal_unique'),
        ),
        migrations.AddField(
            model_name='husbandryeventdeath',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, help_text='Veterinary sign-off, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='husbandryeventweight',
            constraint=models.CheckConstraint(condition=models.Q(('weight_grams__gt', 0)), name='weight_positive_check'),
        ),
        migrations.AddIndex(
            model_name='animalcageassignment',
            index=models.Index(fields=['animal', 'valid_from', 'valid_to'], name='animal_cage_animal__7de64c_idx'),
        ),
        migrations.AddIndex(
            model_name='animalcageassignment',
            index=models.Index(fields=['cage', 'valid_from', 'valid_to'], name='animal_cage_cage_id_b274de_idx'),
        ),
        migrations.AddIndex(
            model_name='animalcageassignment',
            index=models.Index(condition=models.Q(('system_to__isnull', True), ('valid_to__isnull', True)), fields=['animal_id'], name='animal_cage_current_idx'),
        ),
        migrations.AddConstraint(
            model_name='animalcageassignment',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='animal_cage_assignment_valid_range_check'),
        ),
        migrations.AddConstraint(
            model_name='animalcageassignment',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('system_to__isnull', True)), expressions=[('animal', '='), (colony.models.TsTzRange('valid_from', 'valid_to', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&')], name='no_animal_in_two_cages'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['committed', 'committed_with_errors'])), fields=('file_hash',), name='import_batch_hash_committed_unique'),
        ),
        migrations.AddIndex(
            model_name='importrow',
            index=models.Index(fields=['batch', 'row_number'], name='import_row_batch_i_03a751_idx'),
        ),
        migrations.AddConstraint(
            model_name='litter',
            constraint=models.CheckConstraint(condition=models.Q(('weaning_date__isnull', True), ('weaning_date__gte', models.F('birth_date')), _connector='OR'), name='litter_weaning_after_birth_check'),
        ),
        migrations.AddIndex(
            model_name='husbandryevent',
            index=models.Index(fields=['animal', 'event_datetime'], name='husbandry_e_animal__119a36_idx'),
        ),
        migrations.AddIndex(
            model_name='husbandryevent',
            index=models.Index(fields=['cage', 'event_datetime'], name='husbandry_e_cage_id_ccce93_idx'),
        ),
        migrations.AddIndex(
            model_name='husbandryevent',
            index=models.Index(fields=['event_type', 'event_datetime'], name='husbandry_e_event_t_a62a2a_idx'),
        ),
        migrations.AddConstraint(
            model_name='litterparent',
            constraint=models.UniqueConstraint(fields=('litter', 'animal', 'role'), name='litter_parent_unique'),
        ),
        migrations.AddConstraint(
            model_name='rackposition',
            constraint=models.UniqueConstraint(condition=models.Q(('retired_at__isnull', True)), fields=('rack', 'position_label'), name='rack_position_active_unique'),
        ),
        migrations.AddIndex(
            model_name='cagerackpositionassignment',
            index=models.Index(fields=['cage', 'valid_from', 'valid_to'], name='cage_rack_p_cage_id_d96d6e_idx'),
        ),
        migrations.AddIndex(
            model_name='cagerackpositionassignment',
            index=models.Index(fields=['rack_position', 'valid_from', 'valid_to'], name='cage_rack_p_rack_po_a2758d_idx'),
        ),
        migrations.AddIndex(
            model_name='cagerackpositionassignment',
            index=models.Index(condition=models.Q(('system_to__isnull', True), ('valid_to__isnull', True)), fields=['cage'], name='cage_position_current_idx'),
        ),
        migrations.AddConstraint(
            model_name='cagerackpositionassignment',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='cage_position_assignment_valid_range_check'),
        ),
        migrations.AddConstraint(
            model_name='cagerackpositionassignment',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('system_to__isnull', True)), expressions=[('rack_position', '='), (colony.models.TsTzRange('valid_from', 'valid_to'), '&&')], name='no_cage_double_booked_position'),
        ),
        migrations.AddIndex(
            model_name='animallocalidentifier',
            index=models.Index(fields=['identifier_type', 'value'], name='animal_loca_identif_c3b32b_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['retired_at'], name='animal_retired_32d40e_idx'),
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(condition=models.Q(('scope_room__isnull', True)), fields=('user', 'role'), name='user_role_global_unique'),
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(condition=models.Q(('scope_room__isnull', False)), fields=('user', 'role', 'scope_room'), name='user_role_room_unique'),
        ),
    ]
