# Generated by Django 6.1 on 2026-09-01 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0003_death_guard_triggers_and_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animallocalidentifier',
            name='room',
        ),
    ]
