# Generated by Django 6.1 on 2026-09-01 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0004_remove_animallocalidentifier_room'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CageResponsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsibility_type', models.CharField(choices=[('primary', 'Primary'), ('coverage', 'Coverage')], max_length=20)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cage', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='responsibilities', to='colony.cage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cage_responsibilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cage_responsibility',
                'indexes': [models.Index(fields=['cage', 'valid_from', 'valid_to'], name='cage_respon_cage_id_f4eaca_idx'), models.Index(fields=['user', 'valid_from', 'valid_to'], name='cage_respon_user_id_c2d2a7_idx')],
            },
        ),
    ]
