# Generated by Django 6.1 on 2026-09-01 23:58

import colony.models
import django.contrib.postgres.constraints
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0005_cageresponsibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cageresponsibility',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='cage_responsibility_valid_range_check'),
        ),
        migrations.AddConstraint(
            model_name='cageresponsibility',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('responsibility_type', 'primary')), expressions=[('cage', '='), (colony.models.TsTzRange('valid_from', 'valid_to'), '&&')], name='no_overlapping_primary_cage_responsibility'),
        ),
    ]
