# Generated by Django 6.1 on 2026-09-02 16:04

import colony.models
import django.contrib.postgres.constraints
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0006_cageresponsibility_cage_responsibility_valid_range_check_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RackRoomAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('system_from', models.DateTimeField(auto_now_add=True)),
                ('system_to', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('correction_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='corrections', to='colony.rackroomassignment')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='room_assignments', to='colony.rack')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rack_assignments', to='colony.room')),
            ],
            options={
                'db_table': 'rack_room_assignment',
                'indexes': [models.Index(fields=['rack', 'valid_from', 'valid_to'], name='rack_room_a_rack_id_bda3a2_idx'), models.Index(fields=['room', 'valid_from', 'valid_to'], name='rack_room_a_room_id_7bf174_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='rack_room_assignment_valid_range_check'), django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('system_to__isnull', True)), expressions=[('rack', '='), (colony.models.TsTzRange('valid_from', 'valid_to'), '&&')], name='no_rack_in_two_rooms')],
            },
        ),
    ]
