# Generated by Django 6.1 on 2026-09-02 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0009_create_rack_current_room_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='RackCurrentRoom',
            fields=[
                ('rack', models.OneToOneField(db_column='rack_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='current_room', serialize=False, to='colony.rack')),
                ('valid_from', models.DateTimeField()),
            ],
            options={
                'db_table': 'rack_current_room',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='rack',
            name='room',
        ),
    ]
