# Generated by Django 6.1 on 2026-09-02 18:09

import colony.models
import django.contrib.postgres.constraints
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0010_rackcurrentroom_remove_rack_room'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cagerackpositionassignment',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('system_to__isnull', True)), expressions=[('cage', '='), (colony.models.TsTzRange('valid_from', 'valid_to'), '&&')], name='no_cage_in_two_positions'),
        ),
    ]
