# Generated by Django 6.1 on 2026-09-03 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0011_cagerackpositionassignment_no_cage_in_two_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='husbandryevent',
            name='correction_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='corrections', to='colony.husbandryevent'),
        ),
    ]
