# Generated by Django 6.1 on 2026-09-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0012_husbandryevent_correction_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importrow',
            name='parse_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('invalid', 'Invalid'), ('skipped', 'Skipped'), ('committed', 'Committed'), ('undone', 'Undone')], default='pending', max_length=20),
        ),
    ]
